Repository iov-one/iov-core, pull requests merged in 2019-09, with the labels that each got.

#1221 Handle empty multisig array
  packages/iov-bns/src/encode.spec.ts
  packages/iov-bns/src/encode.ts
Labels: merge when green

#1233 Test "any account can return an escrow"
  packages/iov-bns/src/bnsconnection.spec.ts
Labels: merge when green

#1240 Allow empty arrays in Governor.getElectionRules
  CHANGELOG.md
  packages/iov-bns-governance/src/governor.spec.ts
  packages/iov-bns-governance/src/governor.ts
Labels: merge when green

#1241 Validate pubkey in BNS encode
  CHANGELOG.md
  packages/iov-bns/src/encode.spec.ts
  packages/iov-bns/src/encode.ts
  packages/iov-bns/types/encode.d.ts
Labels: merge when green

#1243 Export escrow transaction types
  CHANGELOG.md
  packages/iov-bns/src/index.ts
  packages/iov-bns/types/index.d.ts
Labels: merge when green

#1242 Export proposal action checkers
  CHANGELOG.md
  packages/iov-bns/src/encode.ts
  packages/iov-bns/src/index.ts
  packages/iov-bns/src/types.ts
  packages/iov-bns/types/index.d.ts
  packages/iov-bns/types/types.d.ts
Labels: merge when green

#1246 Add missing decode tests
  CHANGELOG.md
  packages/iov-bns/src/decode.spec.ts
  packages/iov-bns/src/decode.ts
Labels: merge when green

#1247 Add isFullSignature typechecker to BCP
  CHANGELOG.md
  packages/iov-bcp/src/index.ts
  packages/iov-bcp/src/transactions.spec.ts
  packages/iov-bcp/src/transactions.ts
  packages/iov-bcp/types/index.d.ts
  packages/iov-bcp/types/transactions.d.ts
Labels: merge when green

#1248 Resolve circular dependencies
  .eslintrc.json
  package.json
  packages/iov-bcp/src/atomicswapmerger.spec.ts
  packages/iov-bcp/src/atomicswapmerger.ts
  packages/iov-bcp/src/atomicswaptypes.ts
  packages/iov-bcp/src/index.ts
  packages/iov-bcp/src/transactions.ts
  packages/iov-bcp/types/atomicswapmerger.d.ts
  packages/iov-bcp/types/atomicswaptypes.d.ts
  packages/iov-bcp/types/index.d.ts
  packages/iov-bcp/types/transactions.d.ts
  packages/iov-tendermint-rpc/src/adaptor.ts
  packages/iov-tendermint-rpc/src/adaptorforversion.ts
  packages/iov-tendermint-rpc/src/client.spec.ts
  packages/iov-tendermint-rpc/src/client.ts
  packages/iov-tendermint-rpc/types/adaptor.d.ts
  packages/iov-tendermint-rpc/types/adaptorforversion.d.ts
  yarn.lock
Labels: merge when green

#1260 Change multisig ID type to number in multisignatureIdToAddress
  CHANGELOG.md
  packages/iov-bns/src/conditions.spec.ts
  packages/iov-bns/src/conditions.ts
  packages/iov-bns/src/integrationtests/multisignature.spec.ts
  packages/iov-bns/types/conditions.d.ts
Labels: breaking

#1259 Remove unused ReadonlyWallet.canSign
  CHANGELOG.md
  packages/iov-keycontrol/src/wallet.ts
  packages/iov-keycontrol/src/wallets/ed25519wallet.spec.ts
  packages/iov-keycontrol/src/wallets/ed25519wallet.ts
  packages/iov-keycontrol/src/wallets/slip10wallet.spec.ts
  packages/iov-keycontrol/src/wallets/slip10wallet.ts
  packages/iov-keycontrol/types/wallet.d.ts
  packages/iov-keycontrol/types/wallets/ed25519wallet.d.ts
  packages/iov-keycontrol/types/wallets/slip10wallet.d.ts
Labels: breaking

#1257 Change return type of toBytesBigEndian/toBytesLittleEndian to Uint8Array
  CHANGELOG.md
  packages/iov-encoding/src/integers.spec.ts
  packages/iov-encoding/src/integers.ts
  packages/iov-encoding/types/integers.d.ts
Labels: breaking, merge when green

#1261 Remove support for Tendermint 0.29.x – 0.30.x
  CHANGELOG.md
  packages/iov-tendermint-rpc/README.md
  packages/iov-tendermint-rpc/src/adaptorforversion.ts
  packages/iov-tendermint-rpc/src/config.spec.ts
  packages/iov-tendermint-rpc/src/index.ts
  packages/iov-tendermint-rpc/src/v0-29/hasher.spec.ts
  packages/iov-tendermint-rpc/src/v0-29/hasher.ts
  packages/iov-tendermint-rpc/src/v0-29/index.ts
  packages/iov-tendermint-rpc/src/v0-29/requests.ts
  packages/iov-tendermint-rpc/src/v0-29/responses.ts
  packages/iov-tendermint-rpc/types/index.d.ts
  packages/iov-tendermint-rpc/types/v0-29/hasher.d.ts
  packages/iov-tendermint-rpc/types/v0-29/index.d.ts
  packages/iov-tendermint-rpc/types/v0-29/requests.d.ts
  packages/iov-tendermint-rpc/types/v0-29/responses.d.ts
  scripts/tendermint/all_start.sh
  scripts/tendermint/all_stop.sh
Labels: merge when green

#1252 Calculate BlockId from Tendermint header
  CHANGELOG.md
  packages/iov-bns/src/bnsconnection.spec.ts
  packages/iov-bns/src/bnsconnection.ts
  packages/iov-tendermint-rpc/src/adaptor.ts
  packages/iov-tendermint-rpc/src/encodings.spec.ts
  packages/iov-tendermint-rpc/src/encodings.ts
  packages/iov-tendermint-rpc/src/responses.ts
  packages/iov-tendermint-rpc/src/types.ts
  packages/iov-tendermint-rpc/src/v0-31/hasher.spec.ts
  packages/iov-tendermint-rpc/src/v0-31/hasher.ts
  packages/iov-tendermint-rpc/src/v0-31/index.ts
  packages/iov-tendermint-rpc/src/v0-31/responses.ts
  packages/iov-tendermint-rpc/types/adaptor.d.ts
  packages/iov-tendermint-rpc/types/encodings.d.ts
  packages/iov-tendermint-rpc/types/responses.d.ts
  packages/iov-tendermint-rpc/types/types.d.ts
  packages/iov-tendermint-rpc/types/v0-31/hasher.d.ts
Labels: merge when green

#1263 Add connection type parameter to `ChainConnector`
  CHANGELOG.md
  packages/iov-bcp/src/chainconnector.ts
  packages/iov-bcp/types/chainconnector.d.ts
  packages/iov-bns/src/bnsconnector.ts
  packages/iov-bns/types/bnsconnector.d.ts
  packages/iov-ethereum/src/ethereumconnector.ts
  packages/iov-ethereum/types/ethereumconnector.d.ts
  packages/iov-lisk/src/liskconnector.ts
  packages/iov-lisk/types/liskconnector.d.ts
  packages/iov-rise/src/riseconnector.ts
  packages/iov-rise/types/riseconnector.d.ts
Labels: merge when green

#1266 Remove governance constants
  CHANGELOG.md
  packages/iov-bns-governance/src/committees.ts
  packages/iov-bns-governance/src/governor.spec.ts
  packages/iov-bns-governance/src/index.ts
  packages/iov-bns-governance/src/integrationtests/proposals.spec.ts
  packages/iov-bns-governance/src/proposals.ts
  packages/iov-bns-governance/types/committees.d.ts
  packages/iov-bns-governance/types/index.d.ts
  packages/iov-bns-governance/types/proposals.d.ts
  scripts/bnsd/deploy_proposals.js
Labels: merge when green

#1264 Remove TreasurySend proposal type
  CHANGELOG.md
  packages/iov-bns-governance/src/governor.spec.ts
  packages/iov-bns-governance/src/governor.ts
  packages/iov-bns-governance/src/index.ts
  packages/iov-bns-governance/src/integrationtests/proposals.spec.ts
  packages/iov-bns-governance/src/proposals.ts
  packages/iov-bns-governance/types/index.d.ts
  packages/iov-bns-governance/types/proposals.d.ts
Labels: merge when green

#1268 Avoid pointless copy of transaction data
  packages/iov-bns/src/bnsconnection.ts
Labels: merge when green

#1271 Remove old data before copying latest docs
  scripts/travis/mode_docs.sh
Labels: merge when green

#1273 Include tsconfig_repl.json in CLI npm package
  packages/iov-cli/package.json
Labels: merge when green
